@extends('errors.layout')
@section('code', '429')
@section('icon', 'fas fa-hand-paper')
@section('title', 'Too Many Requests')
@section('message', 'You have made too many requests in a short period. Please wait a moment and try again.')
